name: easytransfer
description: "A new transfer project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.10
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  file_picker: ^5.0.0
  permission_handler: ^10.0.0
  intl: ^0.19.0
  intl_utils: ^2.5.0
  provider: ^6.0.0
  network_info_plus: ^5.0.0
  device_info_plus: ^9.0.0
  window_size: ^0.1.0  # 使用已知的兼容版本
  flutter_localizations:
    sdk: flutter
  flutter_p2p_connection:
    path: ./flutter_p2p_connection

dev_dependencies:
  intl_translation: ^0.20.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MiSans
      fonts:
        - asset: fonts/MiSans-Thin.ttf  # 使用细体作为默认字体
        - asset: fonts/MiSans-Regular.ttf
        - asset: fonts/MiSans-Bold.ttf
          weight: 700
        - asset: fonts/MiSans-Light.ttf
          weight: 300
        - asset: fonts/MiSans-Medium.ttf
          weight: 500
        - asset: fonts/MiSans-Semibold.ttf
          weight: 600
        - asset: fonts/MiSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/MiSans-Demibold.ttf
          weight: 400
        - asset: fonts/MiSans-Heavy.ttf
          weight: 800