name: easytransfer
description: "A new transfer project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.10
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  file_picker: ^5.0.0
  permission_handler: ^10.0.0
  intl: ^0.19.0
  intl_utils: ^2.5.0
  provider: ^6.0.0
  network_info_plus: ^5.0.0
  device_info_plus: ^9.0.0
  wifi_direct_plugin:
    path: ./wifi_direct_plugin
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  intl_translation: ^0.20.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
